// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

/**
 * @file
 *
 * This file implements Java class generation.
 */

#include "JavaSourceCodeGenerator.h"
#include "NativeFFI/Java/AfterTypeCheck/Utils.h"
#include "cangjie/AST/Match.h"
#include "cangjie/AST/Utils.h"
#include "cangjie/Utils/CheckUtils.h"
#include "cangjie/Utils/StdUtils.h"

namespace {
using namespace Cangjie::AST;
using namespace Cangjie::Interop::Java;
using namespace Cangjie::Native::FFI;
using TokenKind = Cangjie::TokenKind;

constexpr auto JAVA_PACKAGE = "package";
constexpr auto JAVA_PUBLIC = "public";
constexpr auto JAVA_PROTECTED = "protected";
constexpr auto JAVA_PRIVATE = "private";
constexpr auto JAVA_SEMICOLON = ";";
constexpr auto JAVA_COMMA = ",";
constexpr auto JAVA_WHITESPACE = " ";

constexpr auto JAVA_BOOLEAN = "boolean";
constexpr auto JAVA_SPECIAL_PARAM_NAME = "__init__";

constexpr std::string_view REGISTRY_ID_FIELD_NAME = "$rid";

inline const std::string TAB = "    ";
inline const std::string TAB2 = TAB + TAB;
inline const std::string TAB3 = TAB2 + TAB;

constexpr auto GENERATED_FILE_PREAMBULE =
    "/*\n"
    " * NOTE: This file is auto-generated by cjc.\n"
    " * Do NOT modify it manually.\n"
    " */\n";

bool IsFuncDeclAndNotConstructor(OwnedPtr<Decl>& declPtr)
{
    return declPtr->astKind == ASTKind::FUNC_DECL && !declPtr->TestAttr(Attribute::CONSTRUCTOR);
}
std::string GetModifier(Decl* decl)
{
    if (decl->TestAttr(Attribute::PUBLIC)) {
        return "public ";
    } else {
        return ""; // package-private
    }
}

std::string GetExportedMemberModifier(const Decl& member)
{
    if (member.TestAttr(Attribute::PUBLIC)) {
        return "public ";
    } else if (member.TestAttr(Attribute::PROTECTED)) {
        return "protected ";
    } else {
        CJC_ABORT(); // unreachable state
        return "";
    }
}

std::string FuncParamToString(const OwnedPtr<FuncParam>& p)
{
    CJC_ASSERT(p && p->type && p->type->GetTy());
    std::string res = p->identifier.Val();
    return res;
}

} // namespace

namespace Cangjie::Interop::Java {
JavaSourceCodeGenerator::JavaSourceCodeGenerator(Decl* decl, const BaseMangler& mangler,
    AfterTypeCheckContext& ctx, const std::optional<std::string>& outputFolderPath, const std::string& outputFileName,
    std::string cjLibName, std::vector<Ptr<ExtendDecl>> extends)
    : AbstractSourceCodeGenerator(
          outputFolderPath.value_or(JavaSourceCodeGenerator::DEFAULT_OUTPUT_DIR), outputFileName),
      decl(decl),
      cjLibName(std::move(cjLibName)),
      mangler(mangler),
      ctx(ctx),
      extendDecls(extends)
{
}

void JavaSourceCodeGenerator::ConstructResult()
{
    if (decl->TestAnyAttr(Attribute::IS_BROKEN, Attribute::HAS_BROKEN)) {
        return;
    }

    AddClassDeclaration();
    AddLoadLibrary();
    AddRegistryIdIdField();
    AddProperties();
    AddConstructors();
    AddMethods();
    AddNativeDeleteCJObject();
    AddFinalize();
    AddEndClassParenthesis();
    AddHeader(); // after all because during AST traverse the 'imports' field is accumulating import declarations
}

bool JavaSourceCodeGenerator::IsMemberExportable(const AST::Decl& member) const
{
    CJC_ASSERT(member.outerDecl && member.outerDecl->IsJavaImpl());
    return member.TestAnyAttr(Attribute::PUBLIC, Attribute::PROTECTED);
}


void JavaSourceCodeGenerator::AddHeader()
{
    std::string curPackageName = GetJavaPackage(*decl);
    AddHeaderWithPackageName(curPackageName);
}

void JavaSourceCodeGenerator::AddHeaderWithPackageName(std::string& curPackageName)
{
    std::string header;
    header += GENERATED_FILE_PREAMBULE;
    if (!curPackageName.empty()) {
        header += JAVA_PACKAGE;
        header += JAVA_WHITESPACE;
        header += curPackageName;
        header += JAVA_SEMICOLON;
        header += "\n\n";
    }

    const std::function<std::string(const std::string&)>& mapper = [](const std::string& s) {
        return "import " + s + ";";
    };
    header += Join(imports, "\n", mapper) + "\n";
    header += "import static cangjie.lang.LibraryLoader.loadLibrary;\n";
    header += "import " + GetConstructorMarkerFQName() + ";\n";

    header += "\n";

    res = std::move(header) + res;
}

std::string JavaSourceCodeGenerator::MapCJTypeToJavaType(
    const Ptr<Ty> ty, std::set<std::string>* javaImports, const std::string* curPackageName, bool isNativeMethod)
{
    if (ty->IsCoreOptionType()) {
        return MapCJTypeToJavaType(ty->typeArgs[0], javaImports, curPackageName, isNativeMethod);
    }

    std::string javaType = "";
    auto declTy = Ty::GetDeclOfTy(ty);

    switch (ty->kind) {
        case TypeKind::TYPE_FLOAT64:
            javaType = "double";
            break;
        case TypeKind::TYPE_FLOAT32:
            javaType = "float";
            break;
        case TypeKind::TYPE_INT64:
            javaType = "long";
            break;
        case TypeKind::TYPE_INT32:
            javaType = "int";
            break;
        case TypeKind::TYPE_INT16:
            javaType = "short";
            break;
        case TypeKind::TYPE_UINT16:
            javaType = "char";
            break;
        case TypeKind::TYPE_INT8:
            javaType = "byte";
            break;
        case TypeKind::TYPE_BOOLEAN:
            javaType = JAVA_BOOLEAN;
            break;
        case TypeKind::TYPE_UNIT:
            javaType = "void";
            break;
        case TypeKind::TYPE_INTERFACE:
        case TypeKind::TYPE_CLASS:
            if (IsJArray(*declTy)) {
                return MapCJTypeToJavaType(ty->typeArgs[0], javaImports, curPackageName) + "[]";
            }
            javaType = AddImport(ty, javaImports, curPackageName);
            break;
        case TypeKind::TYPE_STRUCT:
        case TypeKind::TYPE_ENUM:
            javaType = ty->name;
            break;
        default:
            // What?...
            if (ty->name == "String") {
                javaType = "String";
            }
    }

    CJC_ASSERT(!javaType.empty());

    return javaType;
}

std::string JavaSourceCodeGenerator::MapCJTypeToJavaType(const OwnedPtr<Type>& type, std::set<std::string>* javaImports,
    const std::string* curPackageName, bool isNativeMethod)
{
    CJC_ASSERT(type && type->GetTy());
    return MapCJTypeToJavaType(type->GetTy(), javaImports, curPackageName, isNativeMethod);
}

std::string JavaSourceCodeGenerator::MapCJTypeToJavaType(const OwnedPtr<FuncParam>& param,
    std::set<std::string>* javaImports, const std::string* curPackageName, bool isNativeMethod)
{
    CJC_ASSERT(param && param->type && param->type->GetTy());
    return MapCJTypeToJavaType(param->type->GetTy(), javaImports, curPackageName, isNativeMethod);
}

void JavaSourceCodeGenerator::AddClassDeclaration()
{
    // @JavaImpl counterpart java classes could be extended in java.
    std::string modifier = GetModifier(decl);
    res += modifier;
    std::string className = decl->identifier.Val();
    res += "class " + className;

    if (auto classDecl = As<ASTKind::CLASS_DECL>(decl)) {
        Ptr<ClassDecl> superClassPtr = classDecl->GetSuperClassDecl();
        bool isClassInheritedFromClass = !IsJObject(*superClassPtr) && !IsObject(*superClassPtr);

        std::set<Ptr<InterfaceTy>> implementedInterfacesPtrs = classDecl->GetSuperInterfaceTys();
        size_t implementedInterfacesCnt = implementedInterfacesPtrs.size();

        if (isClassInheritedFromClass) {
            res += " extends ";
            res += MapCJTypeToJavaType(superClassPtr->GetTy(), &imports, &classDecl->fullPackageName);
        }

        if (implementedInterfacesCnt > 0) {
            res += " implements ";
            std::set<std::string>* imp = &imports;
            const std::string* package = &classDecl->fullPackageName;
            const std::function<std::string(Ptr<InterfaceTy>)>& transformer = [this, imp, package](Ptr<InterfaceTy> p) {
                return MapCJTypeToJavaType(p, imp, package);
            };
            res += Join(implementedInterfacesPtrs, ", ", transformer);
        }
    }

    res += " {\n";
}

std::string JavaSourceCodeGenerator::AddImport(
    Ptr<Ty> ty, std::set<std::string>* javaImports, const std::string* curPackageName)
{
    std::string javaType = "";

    if (auto classlikety = DynamicCast<ClassLikeTy>(ty)) {
        if (auto clDecl = As<ASTKind::CLASS_LIKE_DECL>(classlikety->commonDecl)) {
            auto [package, topLevelClassName, fullClassName] = Interop::Java::DestructJavaClassName(*clDecl);
            if (!package) {
                return fullClassName;
            }
            if (*package != *curPackageName && *package != IGNORE_IMPORT) {
                javaImports->insert(*package + "." + topLevelClassName);
            }
            javaType = fullClassName;
        }
    }

    return javaType;
}

void JavaSourceCodeGenerator::AddLoadLibrary()
{
    AddWithIndent(TAB, "static {");
    AddWithIndent(TAB2, "loadLibrary(\"" + cjLibName + "\");");
    AddWithIndent(TAB, "}\n");
}

void JavaSourceCodeGenerator::AddRegistryIdIdField()
{
    AddWithIndent(TAB, "private long " + std::string{REGISTRY_ID_FIELD_NAME} + ";\n");
}

void JavaSourceCodeGenerator::AddProperties()
{
    std::vector<Ptr<Decl>> propDecls;
    for (auto extendDecl : extendDecls) {
        for (OwnedPtr<Decl>& declPtr : extendDecl->GetMemberDecls()) {
            if (declPtr->astKind != ASTKind::PROP_DECL || declPtr->TestAttr(Attribute::COMPILER_ADD)) {
                continue;
            }
            auto exportable = declPtr->TestAttr(Attribute::PUBLIC);
            if (exportable) {
                propDecls.emplace_back(declPtr.get());
            }
        }
    }
    for (OwnedPtr<Decl>& declPtr : decl->GetMemberDecls()) {
        if (declPtr->astKind != ASTKind::PROP_DECL || declPtr->TestAttr(Attribute::COMPILER_ADD)) {
            continue;
        }
        if (IsMemberExportable(*declPtr)) {
            propDecls.emplace_back(declPtr.get());
        }
    }
    for (auto& pdecl : propDecls) {
        const PropDecl& propDecl = *StaticAs<ASTKind::PROP_DECL>(pdecl);
        CJC_ASSERT_WITH_MSG(!propDecl.getters.empty(), "property must have at least one getter");
        const std::string type = MapCJTypeToJavaType(propDecl.GetTy(), &imports, &decl->fullPackageName, false);

        std::string varDecl = GetJavaMemberName(propDecl);
        std::string varDeclSuffix = varDecl;
        CJC_ASSERT_WITH_MSG(!varDeclSuffix.empty(), "identifier cannot be an empty string");
        varDeclSuffix[0] = static_cast<char>(toupper(varDeclSuffix[0]));

        std::string getSignature = "get" + varDeclSuffix;

        bool isStaticProp = propDecl.TestAttr(Attribute::STATIC);

        // add getter
        std::string modifier = GetExportedMemberModifier(*pdecl);
        std::string getterStatic = isStaticProp ? "static " : "";
        AddWithIndent(TAB, modifier + getterStatic + "final " + type + " " + getSignature + "() {");
        std::string getRegIdStr = isStaticProp
            ? ""
            : "this." + std::string{REGISTRY_ID_FIELD_NAME};
        AddWithIndent(TAB2, "return " + getSignature + "Impl(" + getRegIdStr + ");");
        AddWithIndent(TAB, "}\n");
        std::string getRegIdNativeStr = isStaticProp
            ? ""
            : "long " + std::string{REGISTRY_ID_FIELD_NAME};
        AddWithIndent(TAB,
            "private " + getterStatic + "final native " + type + " " + getSignature +
                "Impl(" + getRegIdNativeStr + ");\n");

        // add setter
        if (!propDecl.setters.empty()) {
            std::string setterStatic = isStaticProp ? "static " : "";
            std::string setSignature = "set" + varDeclSuffix;
            AddWithIndent(TAB,
                modifier + setterStatic + "final void " + setSignature + "(" + type + " " + varDecl + ") {");
            std::string setRegIdStr = isStaticProp
                ? ""
                : "this." + std::string{REGISTRY_ID_FIELD_NAME} + ", ";
            AddWithIndent(TAB2, setSignature + "Impl(" + setRegIdStr + varDecl + ");");
            AddWithIndent(TAB, "}\n");
            std::string setRegIdNativeStr = isStaticProp
                ? ""
                : "long " + std::string{REGISTRY_ID_FIELD_NAME} + ", ";
            AddWithIndent(
                TAB, "private " + setterStatic + "final native void " + setSignature +
                    "Impl(" + setRegIdNativeStr + type + " " + varDecl + ");\n");
        }
    }
}

std::string JavaSourceCodeGenerator::GenerateFuncParams(
    const std::vector<OwnedPtr<FuncParam>>& params, bool isNativeMethod)
{
    std::set<std::string>* imp = &imports;
    const std::string* curPackage = &decl->fullPackageName;
    std::function<std::string(const OwnedPtr<FuncParam>& ptr)> mapper = [this, imp, curPackage, isNativeMethod](
                                                                            const OwnedPtr<FuncParam>& cur) {
        return MapCJTypeToJavaType(cur, imp, curPackage, isNativeMethod) + " " + cur->identifier.Val();
    };
    return GenerateParams(params, mapper);
}

std::string JavaSourceCodeGenerator::GenerateFuncParamLists(
    const std::vector<OwnedPtr<FuncParamList>>& paramLists, bool isNativeMethod)
{
    std::set<std::string>* imp = &imports;
    const std::string* curPackage = &decl->fullPackageName;
    std::function<std::string(const OwnedPtr<FuncParam>& ptr)> mapper = [this, imp, curPackage, isNativeMethod](
                                                                            const OwnedPtr<FuncParam>& cur) {
        CJC_ASSERT(cur && cur->type && cur->type->GetTy());
        std::string res = MapCJTypeToJavaType(cur, imp, curPackage, isNativeMethod) + " " + cur->identifier.Val();
        return res;
    };
    return GenerateParamLists(paramLists, mapper);
}

std::string JavaSourceCodeGenerator::GenerateFuncParamClasses(const std::vector<OwnedPtr<FuncParamList>>& paramLists)
{
    std::set<std::string>* imp = &imports;
    const std::string* curPackage = &decl->fullPackageName;
    std::function<std::string(const OwnedPtr<FuncParam>& ptr)> mapper = [this, imp, curPackage](
                                                                            const OwnedPtr<FuncParam>& cur) {
        CJC_ASSERT(cur && cur->type && cur->type->GetTy());
        std::string res = MapCJTypeToJavaType(cur, imp, curPackage, false) + ".class";
        return res;
    };
    if (!paramLists.empty() && paramLists[0]) {
        return Join(paramLists[0]->params, ",", mapper);
    }
    return "";
}

std::string JavaSourceCodeGenerator::GenerateConstructorDecl(const FuncDecl& func, bool isForCangjie)
{
    std::string declaration;
    if (!isForCangjie && func.TestAttr(Attribute::PUBLIC)) {
        declaration += JAVA_PUBLIC;
        declaration += JAVA_WHITESPACE;
    } else if (!isForCangjie && func.TestAttr(Attribute::PROTECTED)) {
        declaration += JAVA_PROTECTED;
        declaration += JAVA_WHITESPACE;
    } else if (isForCangjie) {
        declaration += JAVA_PRIVATE;
        declaration += JAVA_WHITESPACE;
    }
    std::string ctorName = decl->identifier.Val();
    declaration.append(ctorName + "(");
    std::string params;
    if (func.funcBody) {
        params += GenerateFuncParamLists(func.funcBody->paramLists);
        if (isForCangjie) {
            if (!params.empty()) {
                params += JAVA_COMMA;
                params += JAVA_WHITESPACE;
            }
            params += GetConstructorMarkerClassName();
            params += JAVA_WHITESPACE;
            params += JAVA_SPECIAL_PARAM_NAME;
        }
    }
    declaration += params;
    declaration += ")";

    return declaration;
}

std::string JavaSourceCodeGenerator::GenerateParams(const std::vector<OwnedPtr<FuncParam>>& params,
    const std::function<std::string(const OwnedPtr<FuncParam>& ptr)>& transform)
{
    return Join(params, ", ", transform);
}

std::string JavaSourceCodeGenerator::GenerateParamLists(const std::vector<OwnedPtr<FuncParamList>>& paramLists,
    const std::function<std::string(const OwnedPtr<FuncParam>& ptr)>& transform)
{
    if (!paramLists.empty() && paramLists[0]) {
        return GenerateParams(paramLists[0]->params, transform);
    }
    return "";
}

/**
 * The important function to generate super call argument and native declaration.
 *
 * @param arg is the super argument with desugared native func
 * @param params is original constructor parameters
 */
std::pair<std::string, std::string> JavaSourceCodeGenerator::GenNativeSuperArgCall(
    const FuncArg& arg, const FuncDecl& nativeFunc, const std::vector<OwnedPtr<FuncParam>>& params)
{
    std::string id = nativeFunc.identifier.Val();
    const std::string keyword = "_super";
    size_t pos = id.rfind(keyword);
    CJC_ASSERT(pos != std::string::npos);
    // The native id should be `superC0A0...`
    id = id.substr(pos + 1);
    // Decode using parameter ids
    const std::string sep = "P";
    std::vector<std::string> parts = Cangjie::Utils::SplitString(id.substr(keyword.length()), sep);
    std::vector<std::string> args;
    std::vector<std::string> nativeParams;
    auto mpTy = [this](const Ptr<Ty> ty) { return MapCJTypeToJavaType(ty, &imports, &decl->fullPackageName); };
    // Skip first part.
    for (size_t i = 1; i < parts.size(); i++) {
        auto pid = Cangjie::Stoi(parts[i]);
        CJC_ASSERT(pid.has_value());
        auto index = pid.value();
        auto& pname = params[static_cast<size_t>(index)]->identifier.Val();
        args.push_back(pname);
        nativeParams.push_back(mpTy(params[static_cast<size_t>(index)]->GetTy()) + " " + pname);
    }
    std::string superCall = id + "(" + Cangjie::Utils::JoinStrings(args, ", ") + ")";
    std::string nativeFnDecl = "private static final native " + mpTy(arg.GetTy()) + " " + id + "(" +
        Cangjie::Utils::JoinStrings(nativeParams, ", ") + ");";
    return std::make_pair(superCall, nativeFnDecl);
}

// Generate super call and collection native func declaration.
std::string JavaSourceCodeGenerator::GenerateSuperCall(
    const CallExpr& call, std::vector<Ptr<FuncDecl>> nativeFuncs,
    const std::vector<OwnedPtr<FuncParam>>& params, std::vector<std::string>& nativeFunctions)
{
    // generate logic
    std::vector<std::string> args;
    for (auto [nativeFunc, originalArg] = std::tuple{nativeFuncs.begin(), call.args.begin()};
        nativeFunc != nativeFuncs.end();
        nativeFunc++, originalArg++) {
            if (*nativeFunc) {
                auto [superCall, superNative] = GenNativeSuperArgCall(**originalArg, **nativeFunc, params);
                args.push_back(superCall);
                nativeFunctions.push_back(superNative);
            } else {
                args.push_back((*originalArg)->expr->ToString());
            }
    }
    return "super(" + Cangjie::Utils::JoinStrings(args, ", ") + ");";
}

std::string JavaSourceCodeGenerator::GenerateConstructorSuperCall(
    const FuncDecl& ctor, std::vector<std::string>& nativeFunctions)
{
    if (!ctx.HasDesugaredJavaImplSuperConstructorCall(ctor)) {
        return "super();";
    }

    auto& originalCall = ctx.GetJavaImplSuperCtorCall(ctor);
    auto argNativeFuncs = ctx.GetJavaImplSuperCtorArgNativeFuncs(ctor);

    CJC_ASSERT(!ctor.funcBody->paramLists.empty());
    auto& params = ctor.funcBody->paramLists[0]->params;
    // Generate super call
    auto superCall = GenerateSuperCall(originalCall, argNativeFuncs, params, nativeFunctions);
    return superCall;
}

void JavaSourceCodeGenerator::AddConstructor(const FuncDecl& ctor, const std::string& superCall, bool isForCangjie)
{
    AddWithIndent(TAB, GenerateConstructorDecl(ctor, isForCangjie) + " {");
    // super call
    if (!superCall.empty()) {
        AddWithIndent(TAB2, superCall);
    }
    if (!isForCangjie) {
        // initCJObject
        auto& params = ctor.funcBody->paramLists[0]->params;
        std::string initCall = GetMangledJniInitCjObjectFuncName(mangler, params, false) + "(";
        if (ctor.funcBody) {
            initCall += GenerateParamLists(ctor.funcBody->paramLists, [](const OwnedPtr<FuncParam>& p) {
                return FuncParamToString(p);
            });
        }
        initCall += ");";

        if (!ctor.outerDecl || !IsImpl(*ctor.outerDecl)) {
            // For JavaImpl classes, `init` call is `void`. registry ID is assigned in cangjie via JNI.
            initCall = std::string{REGISTRY_ID_FIELD_NAME} + " = " + initCall;
        }

        AddWithIndent(TAB2, initCall);
    }
    AddWithIndent(TAB, "}\n");
}

void JavaSourceCodeGenerator::AddConstructor(const FuncDecl& ctor)
{
    std::vector<std::string> nativeFuncitonsForSuperArgs;
    std::string superCall = GenerateConstructorSuperCall(ctor, nativeFuncitonsForSuperArgs);
    CJC_ASSERT_WITH_MSG(!ctor.funcBody->paramLists.empty(), "paramLists cannot be empty");
    auto& params = ctor.funcBody->paramLists[0]->params;
    // Java side constructor
    AddConstructor(ctor, superCall, false);
    // For Cangjie side constructor with marker.
    AddConstructor(ctor, superCall, true);
    // Add native init
    AddNativeInitCJObject(params, ctor);
    // Add native function declarations for super constructor call arguments resolution in java code
    for (auto& fn : nativeFuncitonsForSuperArgs) {
        AddWithIndent(TAB, fn);
    }
}

void JavaSourceCodeGenerator::AddConstructors()
{
    for (OwnedPtr<Decl>& declPtr : decl->GetMemberDecls()) {
        auto fd = As<ASTKind::FUNC_DECL>(declPtr.get());
        if (!fd || !fd->TestAttr(Attribute::CONSTRUCTOR)) {
            continue;
        }
        if (!IsMemberExportable(*fd)) {
            continue;
        }
        if (IsGeneratedJavaImplConstructor(*fd)) {
            continue;
        }
        AddConstructor(*fd);
    }
}

void JavaSourceCodeGenerator::AddInstanceMethod(const FuncDecl& funcDecl)
{
    CJC_ASSERT_WITH_MSG(!funcDecl.funcBody->paramLists.empty(), "paramLists cannot be empty");
    auto& params = funcDecl.funcBody->paramLists[0]->params;
    auto funcIdentifier = GetJavaMemberName(funcDecl);
    auto mangledNativeName = GetMangledMethodName(mangler, params, funcIdentifier);
    auto modifier = GetExportedMemberModifier(funcDecl);
    if (funcDecl.TestAttr(Attribute::OVERRIDE)) {
        AddWithIndent(TAB, "@Override");
    }
    const std::string retType = MapCJTypeToJavaType(funcDecl.funcBody->retType, &imports, &decl->fullPackageName);
    std::string methodSignature = modifier + "final " + retType + " ";
    methodSignature += funcIdentifier + "(";
    std::string argsWithTypes = GenerateFuncParamLists(funcDecl.funcBody->paramLists, false);
    methodSignature += argsWithTypes;
    methodSignature += ") {";
    AddWithIndent(TAB, methodSignature);

    std::string args = std::string{"this."} + std::string{REGISTRY_ID_FIELD_NAME};
    std::string paramList =
        Join(params, ", ", std::function<std::string(const OwnedPtr<FuncParam>&)>([](const OwnedPtr<FuncParam>& p) {
            return FuncParamToString(p);
        }));
    if (!paramList.empty()) {
        args += ", ";
        args += paramList;
    }
    auto funcCall = mangledNativeName + "(" + args + ");";
    if (retType != "void") {
        funcCall = "return " + funcCall;
    }
    AddWithIndent(TAB2, funcCall);
    AddWithIndent(TAB, "}\n");

    argsWithTypes = GenerateFuncParamLists(funcDecl.funcBody->paramLists, true);
    auto comma = (argsWithTypes.empty()) ? "" : ", ";
    AddWithIndent(TAB,
        "private final native " + retType + " " + mangledNativeName +
        "(long " + std::string{REGISTRY_ID_FIELD_NAME} + comma + argsWithTypes + ");\n");
}

void JavaSourceCodeGenerator::AddStaticMethod(const FuncDecl& funcDecl)
{
    CJC_ASSERT_WITH_MSG(!funcDecl.funcBody->paramLists.empty(), "paramLists cannot be empty");
    auto& params = funcDecl.funcBody->paramLists[0]->params;
    auto funcIdentifier = GetJavaMemberName(funcDecl);
    auto mangledNativeName = GetMangledMethodName(mangler, params, funcIdentifier);
    auto modifier = GetExportedMemberModifier(funcDecl);
    const std::string retType = MapCJTypeToJavaType(funcDecl.funcBody->retType, &imports, &decl->fullPackageName);
    std::string argsWithTypes = GenerateFuncParamLists(funcDecl.funcBody->paramLists, false);

    std::string paramList =
        Join(params, ", ", std::function<std::string(const OwnedPtr<FuncParam>&)>([](const OwnedPtr<FuncParam>& p) {
            return FuncParamToString(p);
        }));

    if (mangledNativeName != funcIdentifier) {
        AddWithIndent(TAB, modifier + "static final " + retType + " " + funcIdentifier + "(" + argsWithTypes + ") {");
        auto funcCall = mangledNativeName + "(" + paramList + ");";
        if (retType != "void") {
            funcCall = "return " + funcCall;
        }
        AddWithIndent(TAB2, funcCall);
        AddWithIndent(TAB, "}\n");
    }
    argsWithTypes = GenerateFuncParamLists(funcDecl.funcBody->paramLists, true);
    std::string methodSignature = (mangledNativeName == funcIdentifier ? modifier : "private ")
        + "static final native " + retType + " ";
    methodSignature += mangledNativeName + "(";
    methodSignature += argsWithTypes;
    methodSignature += ");\n";
    AddWithIndent(TAB, methodSignature);
}

void JavaSourceCodeGenerator::AddMethods()
{
    std::vector<Ptr<Decl>> funcDecls;
    for (auto extendDecl : extendDecls) {
        for (OwnedPtr<Decl>& declPtr : extendDecl->GetMemberDecls()) {
            if (declPtr->TestAttr(Attribute::PUBLIC) && IsFuncDeclAndNotConstructor(declPtr)) {
                funcDecls.emplace_back(declPtr.get());
            }
        }
    }
    for (OwnedPtr<Decl>& declPtr : decl->GetMemberDecls()) {
        if (IsMemberExportable(*declPtr) && IsFuncDeclAndNotConstructor(declPtr)) {
            funcDecls.emplace_back(declPtr.get());
        }
    }
    for (auto& fdecl : funcDecls) {
        const FuncDecl& funcDecl = *StaticAs<ASTKind::FUNC_DECL>(fdecl);
        if (funcDecl.funcBody && funcDecl.funcBody->retType) {
            if (funcDecl.TestAttr(Attribute::STATIC)) {
                AddStaticMethod(funcDecl);
            } else {
                AddInstanceMethod(funcDecl);
            }
        }
    }
}

void JavaSourceCodeGenerator::AddEndClassParenthesis()
{
    res += "}\n";
}

/**
 * @param params is original constructor parameters
 */
void JavaSourceCodeGenerator::AddNativeInitCJObject(
    const std::vector<OwnedPtr<Cangjie::AST::FuncParam>>& params, [[maybe_unused]] const FuncDecl& fd)
{
    auto name = GetMangledJniInitCjObjectFuncName(mangler, params, false);
    auto strParams = GenerateFuncParams(params, true);

    std::string signature = "private final native ";
    // For JavaImpl classes, `init` function is `void`.
    signature += "void ";
    signature += name + "(" + strParams + ");\n";
    AddWithIndent(TAB, signature);
}

void JavaSourceCodeGenerator::AddNativeDeleteCJObject()
{
    AddWithIndent(TAB, "private final native void deleteCJObject(long " + std::string{REGISTRY_ID_FIELD_NAME} + ");\n");
}

void JavaSourceCodeGenerator::AddFinalize()
{
    AddWithIndent(TAB, "@Override");
    AddWithIndent(TAB, "protected void finalize() {");
    AddWithIndent(TAB2, "deleteCJObject(this." + std::string{REGISTRY_ID_FIELD_NAME} + ");");
    AddWithIndent(TAB, "}");
}

const std::string JavaSourceCodeGenerator::DEFAULT_OUTPUT_DIR = "java-gen";
const std::string JavaSourceCodeGenerator::IGNORE_IMPORT = "java.lang";
} // namespace Cangjie::Interop::Java
