
// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

/**
 * @file
 *
 * This file declares after-typecheck Java interop stage:
 * - generation of wrapping constructor for java impl reference wrapper.
 */
#ifndef CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_MIRROR_API_STUB
#define CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_MIRROR_API_STUB

#include "AfterTypeCheckStage.h"
#include "InteropLibBridge.h"
#include "InheritanceChecker/MemberSignature.h"
#include "cangjie/AST/Node.h"

namespace Cangjie::Native::FFI::Java {
using namespace Interop::Java;

/**
 * Generates API stubs for Java mirrors.
 * Note: Corresponding API for passing impl objects from java to cangjie is available after this stage (wrap/unwrap).
 */
class GenerateJavaMirrorApiStub : public AfterTypeCheckStage {
public:
    explicit GenerateJavaMirrorApiStub(
        TypeManager& typeManager,
        InteropLibBridge& ilib,
        Interop::Java::Utils& utils,
        const std::unordered_map<Ptr<const AST::InheritableDecl>, MemberMap>&);
protected:
    void Process(AfterTypeCheckContext& ctx) override;
private:
    void Process(AST::ClassLikeDecl& mirror, AfterTypeCheckContext& ctx) const;

    /**
     * Inserts wrapping constructor stub generated by `CreateWrappingConstructorStub` into java impl reference wrapper.
     * @see `CreateWrappingConstructorStub`.
     */
    AST::FuncDecl& InsertWrappingConstructor(AST::ClassDecl& mirror) const;

    AST::FuncDecl& InsertJStringOfStringConstructor(AST::ClassDecl& jstring) const;

    void InsertSyntheticAbstractWrapperMethodStubs(AST::ClassDecl& mirror) const;

    AST::FuncDecl& InsertAbstractJavaReferenceGetterStub(AST::InterfaceDecl& mirror) const;

    /*
     * Creates reference wrapping constructor that accepts `$ref` of `Java_CFFI_JavaEntity`.
     *
     * Assumption: only strong global reference is expected as a reference to java object.
     * Ownership over the reference is taken by the cangjie object under construction.
     */
    OwnedPtr<AST::FuncDecl> CreateWrappingConstructorStub(AST::ClassDecl& mirror) const;

    /**
     * Inserts constructor stub of form `JString(String)`:
     * `public init(s: String)`
     */
    OwnedPtr<AST::FuncDecl> CreateJStringOfStringConstructorStub(AST::ClassDecl& jstring) const;

    /**
     * Generates and inserts javaref getter as javaref field will be in synthetic class
     * that implements current interface.
     *
     * abstract getter
     * public func $getJavaRef(): Java_CFFI_JavaEntity
     */
    OwnedPtr<AST::FuncDecl> CreateAbstractJavaReferenceGetterStub() const;

    TypeManager& typeManager;
    InteropLibBridge& ilib;
    Interop::Java::Utils& utils;

    // Type-check stage member map
    const std::unordered_map<Ptr<const AST::InheritableDecl>, MemberMap>& memberMap;
};

} // namespace Cangjie::Native::FFI::Java

#endif // CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_MIRROR_API_STUB
