
// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

/**
 * @file
 *
 * This file declares after-typecheck Java interop stage:
 * - generation of wrapping constructor for java impl reference wrapper.
 */
#ifndef CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_REFERENCE_FIELD_IN_JOBJECT
#define CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_REFERENCE_FIELD_IN_JOBJECT

#include "AfterTypeCheckStage.h"
#include "InteropLibBridge.h"
#include "cangjie/AST/Node.h"

namespace Cangjie::Native::FFI::Java {
using namespace Interop::Java;

/**
 * Generates API stubs for Java mirrors.
 * Note: Corresponding API for passing impl objects from java to cangjie is available after this stage (wrap/unwrap).
 */
class GenerateJavaReferenceFieldInJObject : public AfterTypeCheckStage {
public:
    explicit GenerateJavaReferenceFieldInJObject(InteropLibBridge& ilib);
protected:
    void Process(AfterTypeCheckContext& ctx) override;
private:
    void Process(AST::ClassLikeDecl& mirror, AfterTypeCheckContext& ctx) const;

    /**
     * Inserts java reference field generated by `CreateJavaReferenceField` into JObject body.
     * @see `CreateJavaReferenceField`.
     */
    AST::VarDecl& InsertJavaReferenceField(AST::ClassDecl& jobject) const;

    OwnedPtr<AST::VarDecl> CreateJavaReferenceField(AST::ClassDecl& jobject) const;

    InteropLibBridge& ilib;
};

} // namespace Cangjie::Native::FFI::Java

#endif // CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_REFERENCE_FIELD_IN_JOBJECT
