
// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

/**
 * @file
 *
 * This file declares after-typecheck Java interop stage:
 * - generation of wrapping constructor stub for java impl reference wrapper.
 */
#ifndef CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_IMPL_API_STUB
#define CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_IMPL_API_STUB

#include "AfterTypeCheckStage.h"
#include "InteropLibBridge.h"
#include "NativeFFI/Java/AfterTypeCheck/JniBridge.h"
#include "cangjie/AST/Node.h"

namespace Cangjie::Native::FFI::Java {
using namespace Interop::Java;

/**
 * Generates API stubs for Java Impls.
 * Note: Corresponding API for passing impl objects from java to cangjie is available after this stage (wrap/unwrap).
 */
class GenerateJavaImplApiStub : public AfterTypeCheckStage {
public:
    explicit GenerateJavaImplApiStub(
        TypeManager& typeManager,
        InteropLibBridge& ilib,
        JniBridge& jni);
protected:
    void Process(AfterTypeCheckContext& ctx) override;
private:
    /**
     * Inserts wrapping constructor stub generated by `CreateWrappingConstructorStub` into java impl reference wrapper.
     * @see `CreateWrappingConstructorStub`.
     */
    AST::FuncDecl& InsertWrappingConstructor(AST::ClassDecl& refWrapper) const;

    /**
     * Generates wrapping constructor stub without body.
     * At later stages, initialization logics is generated.
     * Example:
     * ```cangjie
     * init($obj: Java_CFFI_JavaEntity, $regId: RegistryId)
     * ```
     */
    OwnedPtr<AST::FuncDecl> CreateWrappingConstructorStub(AST::ClassDecl& refWrapper) const;

    TypeManager& typeManager;
    InteropLibBridge& ilib;
    JniBridge& jni;
};

} // namespace Cangjie::Native::FFI::Java

#endif // CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_IMPL_API_STUB
